title: harper lind
theme: jekyll-theme-minimal
title: homepage
description: Bookmark this to keep an eye on my project updates!

lsi: false
safe: true
source: index.html
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
